### ISSUE TITLE
ECVCOFI01 ... Received non-empty PMC source, dying

### ISSUE THREAD

**Issue by wollmers** [wbraswell/rperl#36] opened 2015-10-15 07:32 UTC
Same on OSX and Debian, both under perlbrew

    helmut@helmuts-air:~/rperl$ perl -v
    This is perl 5, version 20, subversion 1 (v5.20.1) built for darwin-2level
    
    helmut@helmuts-air:~/rperl$ rperl -v
    
    This is RPerl version 1.100_002, Long Date 20150911, Star Date 2015.254
    v1.100_002 using RPerl's underscore-is-comma numbering scheme
    v1.100002  using  CPAN's underscore-is-beta  numbering scheme

Example hello_world.pl

    #!/usr/bin/perl
   
    # Learning RPerl, Chapter 1, Exercise 1
    # Print "Hello, world!"; the classic first program for new programmers
    
    # [[[ HEADER ]]]
    use RPerl;
    use strict;
    use warnings;
    our $VERSION = 0.001_000;
    
    # [[[ CRITICS ]]]
    ## no critic qw(ProhibitUselessNoCritic ProhibitMagicNumbers RequireCheckedSyscalls) # USER DEFAULT 1: allow numeric values & print operator
    
    # [[[ OPERATIONS ]]]
    print 'Hello, world!' . "\n";
    
Now we try:

    helmut@helmuts-air:~/rperl$ rperl hello_world.pl 
    ERROR ECVCOFI01, COMPILER, SAVE OUTPUT FILES, MODULE TEMPLATE COPY: Received non-empty PMC source, dying
    helmut@helmuts-air:~/rperl$ which rperl
    /Users/helmut/perl5/perlbrew/perls/perl-5.20.1/bin/rperl
    helmut@helmuts-air:~/rperl$ perl /Users/helmut/perl5/perlbrew/perls/perl-5.20.1/bin/rperl hello_world.pl 
    ERROR ECVCOFI01, COMPILER, SAVE OUTPUT FILES, MODULE TEMPLATE COPY: Received non-empty PMC source, dying

**Comment by jarich** [comment] 2015-10-28 04:54
I'm having exactly the same problem.

**Comment by wbraswell** [comment] 2015-10-28 06:15
Duplicate of 
https://github.com/wbraswell/rperl/issues/37

**Closed by wbraswell** 2015-10-28 06:15 UTC
